CXX:=gcc
CC:=gcc
IDIR=inc
ODIR=obj
SDIR=src

#-------------------------------------------------------------------------------
CFLAGS+= -I./$(IDIR) -fPIC -O3 -m32

SOURCES := $(wildcard $(SDIR)/*.c)

OBJECTS := $(foreach x, $(basename $(SOURCES)), $(x).o)

.PHONY: all

#-------------------------------------------------------------------------------
# target: all 	  - builds the Control Box application
all: createdir classyjson

#-------------------------------------------------------------------------------
# target: createdir  - creates obj dirs
createdir:
	mkdir -p $(ODIR)

#-------------------------------------------------------------------------------
# target: help	  - shows which target there are
help:
	@echo ---Help is on the way---------
	@egrep "^# option:" [Mm]akefile
	@echo ------------------------------
	@egrep "^# target:" [Mm]akefile


#-------------------------------------------------------------------------------
# target: clean	  - removes the binary and .o files
clean:
	rm -f $(ODIR)/*.o *~ libClassyJSON.so
	
#-------------------------------------------------------------------------------
# target: *.o	  - compile the c files to o files
%.o: %.c
	$(CC) -c $< -o $(patsubst $(SDIR)/%,$(ODIR)/%,$@) $(CFLAGS)

#-------------------------------------------------------------------------------
# target: classyjson  - builds classyjson
classyjson: $(OBJECTS)
	@echo  --- Building ClassyJSON shared library for X86 ---
	$(CXX) $(patsubst $(SDIR)/%,$(ODIR)/%,$(OBJECTS)) -o libClassyJSON.so $(CFLAGS) -shared
