CXX:=arm-linux-gnueabihf-gcc
CC:=arm-linux-gnueabihf-gcc
IDIR=inc
ILIB=../inc
ODIR=obj
SDIR=src

#-------------------------------------------------------------------------------
CFLAGS+= -I./$(IDIR) -I./$(ILIB) -Wall

SOURCES := $(wildcard $(SDIR)/*.c)

OBJECTS := $(foreach x, $(basename $(SOURCES)), $(x).o)

.PHONY: all

#-------------------------------------------------------------------------------
# target: all 	  - builds the Control Box application
all: createdir classyjsonprinter

#-------------------------------------------------------------------------------
# target: createdir  - creates obj dirs
createdir:
	mkdir -p $(ODIR)

#-------------------------------------------------------------------------------
# target: help	  - shows which target there are
help:
	@echo ---Help is on the way---------
	@egrep "^# option:" [Mm]akefile
	@echo ------------------------------
	@egrep "^# target:" [Mm]akefile


#-------------------------------------------------------------------------------
# target: clean	  - removes the binary and .o files
clean:
	rm -f $(ODIR)/*.o *~ ClassyTest
	
#-------------------------------------------------------------------------------
# target: *.o	  - compile the c files to o files
%.o: %.c
	$(CC) -c $< -o $(patsubst $(SDIR)/%,$(ODIR)/%,$@) $(CFLAGS)

#-------------------------------------------------------------------------------
# target: classyjsonprinter  - builds classyjsonprinter
classyjsonprinter: $(OBJECTS)
	@echo  --- Building ClassyJSONPrinter for ARM ---
	$(CXX) $(patsubst $(SDIR)/%,$(ODIR)/%,$(OBJECTS)) -o ClassyJSONPrinter $(CFLAGS) -L.. -lClassyJSON -lm